# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-node-test2"
client_id = "bf102f5e873ae0550662a376b06449f9"
application_url = "https://shopify-test4.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-test4.onrender.com/auth/callback",
  "https://shopify-test4.onrender.com/auth/shopify/callback",
  "https://shopify-test4.onrender.com/api/auth/callback",
  "https://shopify-test4.onrender.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-si-matsubara.myshopify.com"
